### ISSUE TITLE
some problem about the structure of data folder

### ISSUE THREAD

**Issue by jiajunhua** [YiwuZhong/Sub-GC#10]
Hello, the following files can be generated by your procedure or downloaded from the Internet ? Where ?  Thanks in advance.
├── flickr30ktalk_label.h5
├── flickr30ktalk.json
├── flickr30k_img_wh.npy

**Comment by YiwuZhong** [comment]
Thanks for your interest. Please follow the instruction of the DATA section in README. All the files can be downloaded on Google Drive.
