### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/COCO_graph_mask_1000_rm_duplicate/391895.npz'

### ISSUE THREAD

**Issue by SikandarBakht** [YiwuZhong/Sub-GC#11]
Hi, I have tried to reproduce the caption generation results but running the script produces the following error: 

FileNotFoundError: [Errno 2] No such file or directory: 'data/COCO_graph_mask_1000_rm_duplicate/391895.npz'

I have unzipped the relevant .zip file from the gdrive link and added it to the proper directory.

**Comment by YiwuZhong** [comment]
Thanks for your interest! I tried downloading the data files and your error didn't happen. Please try re-downloading the zip files and extracting them again. You might also want to check whether 'data/COCO_graph_mask_1000_rm_duplicate/391895.npz' exists in your machine.

**Comment by SikandarBakht** [comment]
Thanks for the help. I was able to fix the issue by redownloading the zip files.
