### ISSUE TITLE
Custom Image captioning

### ISSUE THREAD

**Issue by Sikandar-Bakht** [YiwuZhong/Sub-GC#12]
Hi, can we get the preprocessing code for sub-graph sampling? Also, I'd like some insights into getting custom images captioned with this code. I know there is an option for custom image captioning in the evaluation script but it does not have the accompanying code to produce it. Any help would be appreciated.

**Comment by YiwuZhong** [comment]
Thanks for your interest! This code repo by itself doesn't support custom images. You can find my reply in another previous issue #7.

If you want to inference on custom images, the suggested steps are as follows: (1) extract region features of detected image objects by using the object detector, (2) detect the scene graph by using a scene graph detector, (3) finally decompose the scene graph into subgraphs and decode each into a sentence caption by using our pretrained model.
