### ISSUE TITLE
About Evaluation Metrics

### ISSUE THREAD

**Issue by AmnaSaghi** [YiwuZhong/Sub-GC#13]
Hi, I have tried to run cocoEvalCapDemo.ipynb file for evaluation of COCO images but stuck in this error
![Screenshot_205](https://user-images.githubusercontent.com/67502457/179728317-038d2154-01a9-42df-b1f8-f22677674b6f.png)
Commented all these assertion statements also but not working.

**Comment by YiwuZhong** [comment]
HI @AmnaSaghi, based on your sceenshot, it seems that `hypo` is not a list. However, I don't think `cocoEvalCapDemo.ipynb` was used in my codebase. If you are evaluating our model on COCO datasets, please refer to the evaluation instructions in README.

**Comment by AmnaSaghi** [comment]
Thanks @YiwuZhong  I have solved this issue.
