### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zghorbani** [YiwuZhong/Sub-GC#3]
I have this error in run 'train.sh' with open "cocotalk_label.h5". can you help me why this happens?
 
""File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 116, in h5py.h5f.create
OSError: Unable to create file (unable to open file)""

**Comment by YiwuZhong** [comment]
Thanks for your interests in our work!

According to your description, it seems that the problem came out when your loaded the h5py file. This is likely that your h5py package was broken or wasn't installed correctly. Please carefully follow the instruction in README, reinstall it and try again.
