### ISSUE TITLE
Matching the nouns to the nodes by LCH score

### ISSUE THREAD

**Issue by fortunechen** [YiwuZhong/Sub-GC#4]
Hi zhong, Thanks for your solid work which helps me a lot.

I'd like to ask your about is there a LCH score **_threshold_** which decides two noun node matching or not? If so, what the exact value the threshold is.

Best,
zhuowei

**Comment by YiwuZhong** [comment]
The LCH threshold was set as 2.6 in this project. Hope this helps.

**Comment by fortunechen** [comment]
THX
