### ISSUE TITLE
Sub_graph visualize 

### ISSUE THREAD

**Issue by JingyuLi-code** [YiwuZhong/Sub-GC#6]
How do we visualize the results of the sub_graph 1000 about COCO_graph_mask_1000_rm_duplicate?  For example, objects and relationship, man-on-road.

**Comment by YiwuZhong** [comment]
COCO_graph_mask_1000_rm_duplicate provides the mask on the original full scene graph. You can mask out the nodes, get the sub-graph, and also obtain the class ids for nodes and edges.
