### ISSUE TITLE
错误: 找不到或无法加载主类 edu.stanford.nlp.process.PTBTokenizer

### ISSUE THREAD

**Issue by HN123-123** [YiwuZhong/Sub-GC#9]
我尝试按作者提供的方法评估多样性时，遇到“错误: 找不到或无法加载主类 edu.stanford.nlp.process.PTBTokenizer”导致Bleu_1/2/3/4得分无法计算。
系统中已经成功安装了stanford-corenlp-3.9.2，且测试正常。
请问这个问题是什么引起的，我应该如何解决？？？

**Comment by YiwuZhong** [comment]
Part of the diversity evaluation code comes from the [coco-caption repo](https://github.com/tylin/coco-caption). You can try copying the stanford-corenlp-3.4.1.jar from [coco-caption folder](https://github.com/YiwuZhong/Sub-GC/tree/master/misc/coco-caption/pycocoevalcap/tokenizer) and putting it in the diversity folder.
Update: now stanford-corenlp-3.4.1.jar has been put in the diversity folder.
